CREATE TABLE IF NOT EXISTS wa_tag_prefs (
  tag VARCHAR(255) NOT NULL,
  is_noise TINYINT(1) NOT NULL DEFAULT 0,
  pinned  TINYINT(1) NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (tag)
);
