CREATE TABLE IF NOT EXISTS wa_saved_searches (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  query_json JSON NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_user_name (user_id, name),
  CONSTRAINT fk_saved_search_user FOREIGN KEY (user_id) REFERENCES wa_users(id) ON DELETE CASCADE
);
