CREATE TABLE IF NOT EXISTS wa_media_trash (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  rel_path VARCHAR(1024) NOT NULL,
  rel_path_hash CHAR(64) GENERATED ALWAYS AS (SHA2(rel_path, 256)) STORED,
  type VARCHAR(16) NOT NULL,
  src_path VARCHAR(2048) NOT NULL,
  trash_path VARCHAR(2048) NOT NULL,
  thumb_src_path VARCHAR(2048) NULL,
  thumb_trash_path VARCHAR(2048) NULL,
  taken_ts BIGINT NULL,
  deleted_by_user_id INT NULL,
  deleted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  restored_by_user_id INT NULL,
  restored_at DATETIME NULL,
  purged_by_user_id INT NULL,
  purged_at DATETIME NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'trashed',
  reason VARCHAR(255) NULL,
  UNIQUE KEY uniq_relpath_hash_status (rel_path_hash, status),
  INDEX idx_status_deleted_at (status, deleted_at),
  CONSTRAINT fk_trash_deleted_by FOREIGN KEY (deleted_by_user_id) REFERENCES wa_users(id) ON DELETE SET NULL,
  CONSTRAINT fk_trash_restored_by FOREIGN KEY (restored_by_user_id) REFERENCES wa_users(id) ON DELETE SET NULL,
  CONSTRAINT fk_trash_purged_by FOREIGN KEY (purged_by_user_id) REFERENCES wa_users(id) ON DELETE SET NULL
);
