ALTER TABLE wa_users
  ADD COLUMN password_hash VARCHAR(255) NOT NULL DEFAULT '',
  ADD COLUMN is_admin TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN force_password_change TINYINT(1) NOT NULL DEFAULT 0;
